version: 2

project_name: ecs-meta2env-rs

builds:
  - id: ecs-meta2env-rs
    builder: rust
    binary: ecs-meta2env-rs
    tool: cargo
    command: zigbuild
    targets:
      - x86_64-unknown-linux-musl
      - aarch64-unknown-linux-musl
    flags:
      - --release

archives:
  - formats: [binary]
    name_template: "{{ .ProjectName }}-{{ .Arch }}"

checksum:
  name_template: checksums.txt

dockers_v2:
  - images:
      - ghcr.io/hrko/ecs-meta2env-rs
    tags:
      - "v{{ .Version }}"
      - latest
